
version: "3.0"

services:
  socketio-client-tool:
    build:
      context: .
      target: dev
    image: socketio-client-tool-dev
    container_name: socketio-client-tool-dev
    volumes:
      - .:/app:rw,cached
    ports:
      - "8080:8080"
